### ISSUE TITLE
deposed google_compute_disk fails to destroy with an instance group

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#1046]
In my setup
- disk-raw.tar.gz is uploaded to a bucket with filename `disk-raw-${md5("disk-raw.tar.gz")}.tar.gz`
- a volume is created from that file
- instance template is created that uses the volume as root
- instance group manager is created from the template

I've set lifecycle `create_before_destroy` so that when the `disk-raw.tar.gz` is updated, the md5 sum changes and a everything is re-created. This works, but the first apply will fail, because disks are trying to remove (?) instances that are already being removed by the instance group manager. Running apply again syncs the state correctly.

```
google_compute_instance_group_manager.i.1: Still modifying... (ID: i-europe-west1-c, 10s elapsed)
google_compute_instance_group_manager.i.0: Still modifying... (ID: i-europe-west1-b, 10s elapsed)
google_compute_instance_group_manager.i.2: Still modifying... (ID: i-europe-west1-d, 10s elapsed)
google_compute_instance_group_manager.i.0: Still modifying... (ID: i-europe-west1-b, 20s elapsed)
google_compute_instance_group_manager.i.1: Still modifying... (ID: i-europe-west1-c, 20s elapsed)
google_compute_instance_group_manager.i.2: Still modifying... (ID: i-europe-west1-d, 20s elapsed)
google_compute_instance_group_manager.i[2]: Modifications complete after 23s (ID: i-europe-west1-d)
google_compute_instance_group_manager.i[0]: Modifications complete after 23s (ID: i-europe-west1-b)
google_compute_instance_group_manager.i[1]: Modifications complete after 23s (ID: i-europe-west1-c)
google_compute_instance_template.i.deposed[2]: Destroying... (ID: terraform-20180204104204555100000003)
google_compute_instance_template.i.deposed[0]: Destroying... (ID: terraform-20180204104204554000000002)
google_compute_instance_template.i.deposed[1]: Destroying... (ID: terraform-20180204104204552900000001)
google_compute_instance_template.i.2 (deposed #0): Still destroying... (ID: terraform-20180204104204555100000003, 10s elapsed)
google_compute_instance_template.i.0 (deposed #0): Still destroying... (ID: terraform-20180204104204554000000002, 10s elapsed)
google_compute_instance_template.i.1 (deposed #0): Still destroying... (ID: terraform-20180204104204552900000001, 10s elapsed)
google_compute_instance_template.i.deposed[1]: Destruction complete after 11s
google_compute_instance_template.i.deposed[2]: Destruction complete after 11s
google_compute_instance_template.i.deposed[0]: Destruction complete after 11s
google_compute_disk.ipxe.deposed[2]: Destroying... (ID: ipxe-europe-west1-d-5dc2760de081156857ea361061d431f1)
google_compute_disk.ipxe.deposed[0]: Destroying... (ID: ipxe-europe-west1-b-5dc2760de081156857ea361061d431f1)
google_compute_disk.ipxe.deposed[1]: Destroying... (ID: ipxe-europe-west1-c-5dc2760de081156857ea361061d431f1)
google_compute_disk.ipxe.2 (deposed #0): Still destroying... (ID: ipxe-europe-west1-d-5dc2760de081156857ea361061d431f1, 10s elapsed)
google_compute_disk.ipxe.0 (deposed #0): Still destroying... (ID: ipxe-europe-west1-b-5dc2760de081156857ea361061d431f1, 10s elapsed)
google_compute_disk.ipxe.1 (deposed #0): Still destroying... (ID: ipxe-europe-west1-c-5dc2760de081156857ea361061d431f1, 10s elapsed)
google_compute_disk.ipxe.0 (deposed #0): Still destroying... (ID: ipxe-europe-west1-b-5dc2760de081156857ea361061d431f1, 20s elapsed)
google_compute_disk.ipxe.2 (deposed #0): Still destroying... (ID: ipxe-europe-west1-d-5dc2760de081156857ea361061d431f1, 20s elapsed)
google_compute_disk.ipxe.1 (deposed #0): Still destroying... (ID: ipxe-europe-west1-c-5dc2760de081156857ea361061d431f1, 20s elapsed)
google_compute_disk.ipxe.2 (deposed #0): Still destroying... (ID: ipxe-europe-west1-d-5dc2760de081156857ea361061d431f1, 30s elapsed)
google_compute_disk.ipxe.0 (deposed #0): Still destroying... (ID: ipxe-europe-west1-b-5dc2760de081156857ea361061d431f1, 30s elapsed)
google_compute_disk.ipxe.1 (deposed #0): Still destroying... (ID: ipxe-europe-west1-c-5dc2760de081156857ea361061d431f1, 30s elapsed)
google_compute_disk.ipxe.2 (deposed #0): Still destroying... (ID: ipxe-europe-west1-d-5dc2760de081156857ea361061d431f1, 40s elapsed)
google_compute_disk.ipxe.0 (deposed #0): Still destroying... (ID: ipxe-europe-west1-b-5dc2760de081156857ea361061d431f1, 40s elapsed)
google_compute_disk.ipxe.1 (deposed #0): Still destroying... (ID: ipxe-europe-west1-c-5dc2760de081156857ea361061d431f1, 40s elapsed)
google_compute_disk.ipxe.0 (deposed #0): Still destroying... (ID: ipxe-europe-west1-b-5dc2760de081156857ea361061d431f1, 50s elapsed)
google_compute_disk.ipxe.1 (deposed #0): Still destroying... (ID: ipxe-europe-west1-c-5dc2760de081156857ea361061d431f1, 50s elapsed)
google_compute_disk.ipxe.0 (deposed #0): Still destroying... (ID: ipxe-europe-west1-b-5dc2760de081156857ea361061d431f1, 1m0s elapsed)
Releasing state lock. This may take a few moments...

Error: Error applying plan:

3 error(s) occurred:

* google_compute_disk.ipxe[2] (destroy): 1 error(s) occurred:

* google_compute_disk.ipxe.2 (deposed #0): 1 error(s) occurred:

* google_compute_disk.ipxe.2 (deposed #0): The resource 'projects/myproject/zones/europe-west1-d/instances/i-europe-west1-d-6rpl' was not found

* google_compute_disk.ipxe[1] (destroy): 1 error(s) occurred:

* google_compute_disk.ipxe.1 (deposed #0): 1 error(s) occurred:

* google_compute_disk.ipxe.1 (deposed #0): The resource 'projects/myproject/zones/europe-west1-c/instances/i-europe-west1-c-22h2' was not found

* google_compute_disk.ipxe[0] (destroy): 1 error(s) occurred:

* google_compute_disk.ipxe.0 (deposed #0): 1 error(s) occurred:

* google_compute_disk.ipxe.0 (deposed #0): The resource 'projects/myproject/zones/europe-west1-b/instances/i-europe-west1-b-64js' was not found
```

**Comment by ndmckinley** [comment]
Hi!  Thanks for reporting this issue.

It would be helpful if you could post a repro config - it sounds like the order of destruction is the problem, and I suspect we can fix that by making disks ignore detach errors if they're already detached.  It might be easier to tweak the config, though.  Even if it isn't, a repro config will help me verify that I have fixed the problem.

**Comment by matti** [comment]
@ndmckinley here you go: https://github.com/matti/repro-terraform-provider-google-issue-1046

you need to apply twice - each time with different "trigger"

**Comment by ndmckinley** [comment]
Thanks!

**Comment by paddycarver** [comment]
Is this potentially related to #54?

**Comment by danawillow** [comment]
So we do check that the instance exists before we detach the disk from it, and at the time that we call detach, the instance still exists. However, the operation is asynchronous, and so while we're waiting for it to return, the IGM deletes the instance and our operation fails.

I think the best way forward is just to check the return error from the detach call, and if it's a 404 ignore it.
