### ISSUE TITLE
`host` not supported for google_sql_user setting on 2nd gen Cloud SQL?

### ISSUE THREAD

**Issue by czka** [terraform-providers/terraform-provider-google#1611]
https://www.terraform.io/docs/providers/google/r/sql_user.html reads (bold highlights by me):
> host - (Optional) The host the user can connect from. This is **only** supported for **first** generation SQL instances. **Don't** set this field for **second** generation SQL instances. Can be an IP address. Changing this forces a new resource to be created.

But, as you can see on the screenshot below, Google console does allow setting `host` for 2nd generation Cloud SQL user. So who's correct?

![image](https://user-images.githubusercontent.com/1593918/41109791-20ed44d6-6a78-11e8-8192-676633f738c3.png)

**Comment by danawillow** [comment]
Thanks, I could have sworn I fixed this but apparently I forgot. PR incoming.

**Comment by czka** [comment]
@danawillow How long does typically take before such change is copied over to https://www.terraform.io/docs/providers/google? https://www.terraform.io/docs/providers/google/r/sql_user.html#host is still wrong as of writing this.

**Comment by danawillow** [comment]
We usually update the website with each release, that way the documentation lines up with the code that's available.

**Comment by czka** [comment]
But you have an obvious error in the docs now. And you are going to wait until the next release to have it fixed?

**Comment by danawillow** [comment]
We could do it now, but then we'd have to make sure we don't end up with other errors by saying that we support certain features that haven't come out yet. @paddycarver, is it possible to cherry-pick one change into the website?

**Comment by paddycarver** [comment]
Possible and not difficult at all. I'll get #1635 cherrypicked onto the website and deployed now.
