### ISSUE TITLE
Terraform validate fails with google_compute_health_check and dynamic blocks

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-google#6295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.24
+ provider.google v3.20.0
```

### Affected Resource(s)

* google_compute_health_check

### Terraform Configuration Files

```tf
resource "google_compute_health_check" "hc" {
  #used for internal backend
  project             = var.project
  name                = "health-check"
  check_interval_sec  = 10
  timeout_sec         = 5
  healthy_threshold   = 2
  unhealthy_threshold = 10
  dynamic "https_health_check" {
    for_each = var.tls_enable ? ["enabled"] : []
    content {
      request_path = var.health_check
      port         = 8200
    }
  }
  dynamic "http_health_check" {
    for_each = var.tls_enable ? [] : ["enabled"]
    content {
      request_path = var.health_check
      port         = 8200
    }
  }
}
```

### Expected Behavior

Validate should pass

### Actual Behavior

```
Error: "http2_health_check": only one of `http2_health_check,http_health_check,https_health_check,ssl_health_check,tcp_health_check` can be specified, but `http_health_check,https_health_check` were specified.
on .terraform/modules/gcp/lb.tf line 16, in resource "google_compute_health_check" "hc":
16: resource "google_compute_health_check" "hc" {
Error: "https_health_check": only one of `http2_health_check,http_health_check,https_health_check,ssl_health_check,tcp_health_check` can be specified, but `http_health_check,https_health_check` were specified.
on .terraform/modules/gcp/lb.tf line 16, in resource "google_compute_health_check" "hc":
16: resource "google_compute_health_check" "hc" {
Error: "tcp_health_check": only one of `http2_health_check,http_health_check,https_health_check,ssl_health_check,tcp_health_check` can be specified, but `http_health_check,https_health_check` were specified.
on .terraform/modules/gcp/lb.tf line 16, in resource "google_compute_health_check" "hc":
16: resource "google_compute_health_check" "hc" {
Error: "http_health_check": only one of `http2_health_check,http_health_check,https_health_check,ssl_health_check,tcp_health_check` can be specified, but `http_health_check,https_health_check` were specified.
on .terraform/modules/gcp/lb.tf line 16, in resource "google_compute_health_check" "hc":
16: resource "google_compute_health_check" "hc" {
Error: "ssl_health_check": only one of `http2_health_check,http_health_check,https_health_check,ssl_health_check,tcp_health_check` can be specified, but `http_health_check,https_health_check` were specified.
on .terraform/modules/gcp/lb.tf line 16, in resource "google_compute_health_check" "hc":
16: resource "google_compute_health_check" "hc" {
```

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

This was working in 3.19.

**Comment by venkykuberan** [comment]
https_health_check conflicts with http_health_check, you need to use one of them. We have that validation in place for some time, i can repro that error in version 3.5 and later.

**Comment by morgante** [comment]
I believe this was likely fixed with #6286.

**Comment by mbrancato** [comment]
Hi @venkykuberan  - these are dynamic blocks with alternate results in the conditional set. It is impossible for them to both be set at the same time.

**Comment by venkykuberan** [comment]
I see that @mbrancato,  as @morgante pointed out it will be fixed in that PR.

**Comment by Pradeepta93** [comment]
This is is not yet resolved, Can we expect any official update on this. Also, most of the LB modules are not working as expected. By when can we expect a fix to these issues. As we are planning to use the CFT module of GCP for the load balancer.
